export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
export const TOGGLE_LOADER = "TOGGLE_LOADER";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";